# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          BergauseFunc's Blog 
paginate:       5
baseurl:        ""
url:            ""

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown



# Gems
gems:
  - jekyll-paginate
